### ISSUE TITLE
Object model is not user-friendly

### ISSUE THREAD

**Issue by DSotnikov** [ballerina-platform/module-salesforcerest#7]
Looks like the current object-model exposed by the connector is just a duplication of the native REST API and still requires user to learn how Salesforce functions internally. What I would love to do is something like:

foreach contact in salesforce.contacts {
  contact.fullname = contact.firstname + contact.lastname
}

And get tab completion for all the properties!

That way, my learning curve will be non-existent and the connector would let me go and script Salesforce very quickly by just exploring the objects and their properties.

**Comment by anupama-pathirage** [comment]
Closing this issue as we no longer maintain this codebase.
